
// libraries
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import memoji from '../public/images/my-memoji.png';
import Link from "next/link"

// react-icons
import { LuSprout } from 'react-icons/lu';
import { RiPlantFill, RiLeafFill } from 'react-icons/ri';
import { CgSmile } from 'react-icons/cg'
import { BsInstagram, BsLinkedin, BsGlobe, BsGithub } from 'react-icons/bs'
import { AiFillGithub, AiFillInstagram, AiFillLinkedin } from 'react-icons/ai';

// components
import Navbar from './components/Navbar'
import About from './components/About'
import Experience from './components/Experience'
import ProjectPreview from './components/ProjectPreview'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const tech = [
    "Javascript",
    "React.js",
    "Node.js",
    "Python",
    "Java",
    "C++"
  ]


  return (
    <div>
      <div className='mx-auto w-[90%] md:w-[80%] lg:w-[70%]'>
        <Head>
          <title>My portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* NAVBAR SECTION */}
        <section>
          <Navbar />
        </section>

        {/* HOME SECTION */}
        <section id="home" className='grid gap-8 md:grid-cols-[2fr_1fr] mb-4'>
          {/* card 1 */}
          <div className="bg-zinc-200 h-auto rounded-3xl p-10 lg:p-20 flex flex-col gap-16 bg-[url('../public/images/gradient-bg.jpg')] bg-cover lg:h-[40rem]">
            <h1 className='text-4xl font-semibold md:text-5xl'>
              {"Jadrian Tan"}
            </h1>
            <p className='flex-1 md:text-xl'>
              Welcome to my digital abode! Explore the wonders of my virtual realm, where passion meets pixels and creativity thrives.
            </p>
            {/* emojis */}
            <div className='flex flex-col gap-3 items-center lg:flex-row'>
              <button className='bg-black text-white rounded-full font-small py-2 px-4 w-40 md:font-mx md:text-xl md:py-3 md:px-12'>
                Say Hi
              </button>
              <div className='flex gap-4'>
                {/* <BsGlobe href='#' className='hover:cursor-pointer md:text-2xl' /> */}
                <BsInstagram className='hover:cursor-pointer md:text-2xl' />
                <BsLinkedin className='hover:cursor-pointer md:text-2xl' />
                <BsGithub className='hover:cursor-pointer md:text-2xl' />
              </div>
            </div>
          </div>
          {/* card 2 */}
          {/* <div className=" bg-zinc-200 h-[30rem] rounded-3xl p-10 bg-[url('../public/images/jadrian2.jpg')] bg-cover bg-center lg:h-[40rem]">
          </div> */}
          <div className='relative h-auto  overflow-hidden lg:mt-20 lg:h-96 lg:w-auto '>
            <Image src={memoji} layout='fill' className='object-contain h-60 w-96 ' />
          </div>
        </section>

        {/* PROJECT SECTION */}
        <section key="1" id="project" className="grid grid-cols-1 lg:grid-cols-2 gap-4 my-4">
          <ProjectPreview
            name="Sentiment Analysis with FNN & RNN"
            description="In this project, I explore the performance of various deep learning models on a text classification task using Word2Vec features. I first pre-process the dataset and extract features using the Word2Vec model. These features serve as input to different deep learning architectures, namely a Multi-Layer Perceptron (MLP), a Simple RNN, a GRU (Gated Recurrent Unit), and an LSTM (Long Short-Term Memory) network. The goal is to compare the accuracy of these models in classifying the text data and identify the most effective architecture for our specific dataset. The performance metrics are visualized using a graph to provide a clear comparison among the different models."
            imageUrl=""
            bgColor="#6B5CE5"
            dark
          />
          <ProjectPreview
            name="Color-Based Object Detection"
            description="..."
            imageUrl=""
            bgColor="#313443"
            dark
          />
          <ProjectPreview
            name=""
            description="Next-gen social media"
            imageUrl=""
            bgColor="#D7DBE3"
          />
          <ProjectPreview
            name="HuntSC"
            description="Next-gen social media"
            imageUrl=""
            bgColor="#4E4E57"
            dark
          />
        </section>


        {/* ABOUT SECTION */}
        <section id="about" className='gap-4 grid lg:grid-cols-[2fr_1fr] my-4'>
          {/* card 1 */}
          <div className="bg-zinc-200 h-auto rounded-3xl p-10 lg:p-20 flex flex-col gap-16 bg-[url('../public/images/gradient-bg.jpg')] bg-cover ">

            <h1 className='mb-[-10px] text-roboto text-black text-4xl font-semibold md:text-5xl'>
              {"About Me"}
            </h1>
            {/* whoami */}
            <p className=" md:text-xl">
              I am a first-gen Malaysian tech trooper, currently enrolled at the University of Southern California. I'm pursuing a B.S. and M.S. in Computer Science, and I'm on track to graduate in May 2024.
            </p>
            <p className="md:text-xl my-[-40px]">Here are some technologies I have been Working With: </p>
            <ul className="list-none grid grid-cols-2 gap-2 text-xl">
              <li className="">
                <span className="text-base font-extralight px-[1rem]">{"▹ "}</span>{"Javascript"}
              </li>
              <li className="">
                <span className="text-base font-extralight px-[1rem]">{"▹ "}</span>{"Java"}
              </li>
              <li className="">
                <span className="text-base font-extralight px-[1rem]">{"▹ "}</span>{"React.js"}
              </li>
              <li className="">
                <span className="text-base font-extralight px-[1rem]">{"▹ "}</span>{"Node.js"}
              </li>
              <li className="">
                <span className="text-base font-extralight px-[1rem]">{"▹ "}</span>{"Python"}
              </li>
              <li className="">
                <span className="text-base font-extralight px-[1rem]">{"▹ "}</span>{"C++"}
              </li>
            </ul>
            {/* outside of work woohoo */}
            <p className="mt-[-20px] md:text-xl">
              Outside of work, you'll find me getting a good sweat session at the gym, exploring scenic hiking trails, and fearlessly experimenting in the kitchen.
            </p>
          </div>
          {/* card 2 */}
          <div className=" bg-zinc-200 h-[40rem] w-auto rounded-3xl p-10 bg-[url('../public/images/jadrian2.jpg')] bg-cover bg-center lg:h-auto">
          </div>
        </section>

        {/* EXPERIENCE */}
        <section className='my-4'>
          <Experience />
        </section>


        {/* ALTERNATIVE: ABOUT SECTION */}
        {/* <section id="about" className=' grid gap-0 md:grid-cols-[1fr_6fr] mb-4'>
          <div className="flex gap-2 md:flex-col justify-center items-center h-[4rem] max-h-auto bg-gradient-to-r from-zinc-800 to-zinc-500 p-5 rounded-t-3xl md:rounded-tl-3xl md:rounded-tr-none md:rounded-bl-3xl md:h-[28rem]">
            <span className='text-white font-light text-xl md:text-2xl'>A</span>
            <span className='text-white font-light text-xl md:text-2xl'>B</span>
            <span className='text-white font-light text-xl md:text-2xl'>O</span>
            <span className='text-white font-light text-xl md:text-2xl'>U</span>
            <span className='text-white font-light text-xl md:text-2xl'>T</span>
            <br />
            <span className='text-white font-light text-xl md:text-2xl'>M</span>
            <span className='text-white font-light text-xl md:text-2xl'>E</span>
          </div>
          <About />
        </section> */}

      </div>



      {/* FOOTER w/o ratio */}
      <section>
        <div className='flex flex-col items-center font-extralight text-black text-xl my-4'>
          <span>
            {"© 2023 | Built and designed by Jadrian Tan"}
          </span>
          {/* <Link href="#" className='my-2 h-auto w-[200px] text-center text-white bg-zinc-800 rounded-full'>
            Back to top
          </Link> */}
        </div>
      </section>

    </div>

  )
}
