
// libraries
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import memoji from '../public/images/my-memoji.png';
import Link from "next/link"

// react-icons
import { LuSprout } from 'react-icons/lu';
import { RiPlantFill, RiLeafFill } from 'react-icons/ri';
import { CgSmile } from 'react-icons/cg'
import { BsInstagram, BsLinkedin, BsGlobe, BsGithub } from 'react-icons/bs'
import { AiFillGithub, AiFillInstagram, AiFillLinkedin } from 'react-icons/ai';

// components
import Navbar from './components/Navbar'
import About from './components/About'
import Experience from './components/Experience'
import ProjectPreview from './components/ProjectPreview'

// images
import huntsc from '../public/images/huntsc.png';
import nlp from '../public/images/nlp.png';
import recapp from '../public/images/uscrecapp.png';
import vision from '../public/images/vision.png';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const tech = [
    "Javascript",
    "React.js",
    "NodeJS/ExpressJS",
    "Python",
    "Java",
    "C++"
  ]


  return (
    <div>
      <div className='mx-auto w-[90%] md:w-[80%] lg:w-[70%]'>
        <Head>
          <title>My portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* NAVBAR SECTION */}
        <section>
          <Navbar />
        </section>

        {/* HOME SECTION */}
        <section id="home" className='grid gap-8 md:grid-cols-[2fr_1fr] mb-4'>
          {/* card 1 */}
          <div className="bg-zinc-200 h-auto rounded-3xl p-10 lg:p-20 flex flex-col gap-16 bg-[url('../public/images/gradient-bg.jpg')] bg-cover lg:h-[40rem]">
            <h1 className='text-4xl font-semibold md:text-5xl'>
              {"Jadrian Tan"}
            </h1>
            <p className='flex-1 md:text-xl'>
              Welcome to my digital abode! Explore the wonders of my virtual realm, where passion meets pixels and creativity thrives.
            </p>
            {/* emojis */}
            <div className='flex flex-col gap-3 items-center lg:flex-row'>
            <a href="mailto:jwtan@usc.edu" className="underline-none">
              <button className='bg-black text-white rounded-full font-small py-2 px-4 w-40 md:font-mx md:text-xl md:py-3 md:px-12'>
                Say Hi
              </button>
            </a>
            <div className='flex gap-4'>
              <a href="https://www.instagram.com/ja.drian/" target="_blank" rel="noopener noreferrer" className='hover:cursor-pointer md:text-2xl'>
                <BsInstagram />
              </a>
              <a href="https://www.linkedin.com/in/jadriantan/" target="_blank" rel="noopener noreferrer" className='hover:cursor-pointer md:text-2xl'>
                <BsLinkedin />
              </a>
              <a href="https://github.com/jadriant" target="_blank" rel="noopener noreferrer" className='hover:cursor-pointer md:text-2xl'>
                <BsGithub />
              </a>
            </div>
            </div>
          </div>
          {/* card 2 */}
          {/* <div className=" bg-zinc-200 h-[30rem] rounded-3xl p-10 bg-[url('../public/images/jadrian2.jpg')] bg-cover bg-center lg:h-[40rem]">
          </div> */}
          <div className='relative h-auto  overflow-hidden lg:mt-20 lg:h-96 lg:w-auto '>
            <Image src={memoji} layout='fill' className='object-contain h-60 w-96 ' />
          </div>
        </section>

        {/* PROJECT SECTION */}
        <section key="1" id="project" className="grid grid-cols-1 lg:grid-cols-2 gap-4 my-4">
          <ProjectPreview
            name="Sentiment Analysis with ML"
            description="The project analyzes customer reviews to gauge sentiment, utilizing data preprocessing and machine learning models."
            imageUrl={nlp}
            bgColor="#6B5CE5"
            dark
            githubLink="https://github.com/jadriant/ML-projects/tree/main/sentiment_analysis"
          />
          <ProjectPreview
            name="Color-Based Object Detection"
            description="The project uses unique color representations to detect colorful objects in images."
            imageUrl={vision}
            bgColor="#313443"
            dark
            githubLink="https://github.com/jadriant/ML-projects/tree/main/color-based_object_detection"
          />
          <ProjectPreview
            name="HuntSC"
            description="A platform for USC student orgs to find and add venues for events."
            imageUrl={huntsc}
            bgColor="#D7DBE3"
            githubLink="https://github.com/jadriant/FullStack-projects/tree/main/huntsc"
          />
          <ProjectPreview
            name="USCRecApp"
            description="Book your spot at USC's rec centers with my user-friendly Android app, ensuring efficient capacity management and timely reminders."
            imageUrl={recapp}
            bgColor="#4E4E57"
            dark
            githubLink="https://github.com/jadriant/FullStack-projects/tree/main/USCRecApp"
          />
        </section>


        {/* ABOUT SECTION */}
        <section id="about" className='gap-4 grid lg:grid-cols-[2fr_1fr] my-4'>
          {/* card 1 */}
          <div className="bg-zinc-200 h-auto rounded-3xl p-10 lg:p-20 flex flex-col gap-16 bg-[url('../public/images/gradient-bg.jpg')] bg-cover ">

            <h1 className='mb-[-10px] text-roboto text-black text-4xl font-semibold md:text-5xl'>
              {"About Me"}
            </h1>
            {/* whoami */}
            <p className=" md:text-xl">
              I am a first-gen Malaysian tech trooper, currently enrolled at the University of Southern California. I'm pursuing a B.S. and M.S. in Computer Science, and I'm on track to graduate in May 2024.
            </p>
            <p className="md:text-xl my-[-40px]">Here are some technologies I have been Working With: </p>
            <ul className="list-none grid grid-cols-2 gap-2 text-[10px] sm:text-xl">
              <li>
                <span className="font-extralight px-[1rem]">{"▹ "}</span>Javascript
              </li>
              <li>
                <span className="font-extralight px-[1rem]">{"▹ "}</span>Java
              </li>
              <li>
                <span className="font-extralight px-[1rem]">{"▹ "}</span>React.js
              </li>
              <li>
                <span className="font-extralight px-[1rem]">{"▹ "}</span>Node.js
              </li>
              <li>
                <span className="font-extralight px-[1rem]">{"▹ "}</span>Python
              </li>
              <li>
                <span className="font-extralight px-[1rem]">{"▹ "}</span>C++
              </li>
            </ul>


            {/* outside of work woohoo */}
            <p className="mt-[-20px] md:text-xl">
              Outside of work, you'll find me getting a good sweat session at the gym, exploring scenic hiking trails, and fearlessly experimenting in the kitchen.
            </p>
          </div>
          {/* card 2 */}
          <div className=" bg-zinc-200 h-[40rem] w-auto rounded-3xl p-10 bg-[url('../public/images/jadrian2.jpg')] bg-cover bg-center lg:h-auto">
          </div>
        </section>

        {/* EXPERIENCE */}
        <section className='my-4'>
          <Experience />
        </section>


        {/* ALTERNATIVE: ABOUT SECTION */}
        {/* <section id="about" className=' grid gap-0 md:grid-cols-[1fr_6fr] mb-4'>
          <div className="flex gap-2 md:flex-col justify-center items-center h-[4rem] max-h-auto bg-gradient-to-r from-zinc-800 to-zinc-500 p-5 rounded-t-3xl md:rounded-tl-3xl md:rounded-tr-none md:rounded-bl-3xl md:h-[28rem]">
            <span className='text-white font-light text-xl md:text-2xl'>A</span>
            <span className='text-white font-light text-xl md:text-2xl'>B</span>
            <span className='text-white font-light text-xl md:text-2xl'>O</span>
            <span className='text-white font-light text-xl md:text-2xl'>U</span>
            <span className='text-white font-light text-xl md:text-2xl'>T</span>
            <br />
            <span className='text-white font-light text-xl md:text-2xl'>M</span>
            <span className='text-white font-light text-xl md:text-2xl'>E</span>
          </div>
          <About />
        </section> */}

      </div>



      {/* FOOTER w/o ratio */}
      <section>
        <div className='flex flex-col items-center font-extralight text-black text-xs sm:text-xl my-4'>
          <span>
            {"© 2023 | Built and designed by Jadrian Tan"}
          </span>
          <Link href="#" className=' text-xl my-2 h-auto w-[200px] text-center text-white bg-zinc-800 rounded-full block md:hidden'>
            Back to top
          </Link>
        </div>

      </section>

    </div>

  )
}
